services:
    # MySQL Service
    mysql:
        image: mysql:latest
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: db
        ports:
            - '3306:3306'
        volumes:
            - mysql_data:/var/lib/mysql

    # Redis Service
    redis:
        image: redis:latest
        container_name: redis
        ports:
            - '6379:6379'
        volumes:
            - redis_data:/data

    # Kafka Service
    kafka:
        image: confluentinc/cp-kafka:7.8.0
        container_name: kafka
        hostname: kafka1
        ports:
            - '9092:9092'
        environment:
            KAFKA_NODE_ID: 1
            KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
            KAFKA_LISTENERS: 'INTERNAL://kafka1:29092,CONTROLLER://kafka1:29093,EXTERNAL://0.0.0.0:9092'
            KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafka1:29092,EXTERNAL://kafka:9092'
            KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
            KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka1:29093'
            KAFKA_PROCESS_ROLES: 'broker,controller'
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
            CLUSTER_ID: 'ZGI5YjMwZmNiODI1MTFlZm'
            KAFKA_LOG_DIRS: '/tmp/kraft-logs'

    # Spring Boot Backend
    backend:
        build: ./back-end
        container_name: spring-backend
        depends_on:
            - mysql
            - redis
            - kafka
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/db
            SPRING_DATASOURCE_USERNAME: root
            SPRING_DATASOURCE_PASSWORD: root
            SPRING_REDIS_HOST: redis
            SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
            SPRING_PROFILES_ACTIVE: default
            CLOUDINARY_URL: ${CLOUDINARY_URL}
            CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
            CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
            CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}

            GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
            GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}

            FACEBOOK_CLIENT_ID: ${FACEBOOK_CLIENT_ID}
            FACEBOOK_CLIENT_SECRET: ${FACEBOOK_CLIENT_SECRET}

            PAYPAL_CLIENT_ID: ${PAYPAL_CLIENT_ID}
            PAYPAL_CLIENT_SECRET: ${PAYPAL_CLIENT_SECRET}
            PAYPAL_MODE: ${PAYPAL_MODE}

            MAIL_HOST: ${MAIL_HOST}
            MAIL_PORT: ${MAIL_PORT}
            MAIL_USERNAME: ${MAIL_USERNAME}
            MAIL_PASSWORD: ${MAIL_PASSWORD}

        ports:
            - '8080:8080'

    # Admin Frontend
    admin-frontend:
        build: ./front-end/admin-ui
        container_name: admin-frontend
        ports:
            - '3001:80'
        depends_on:
            - backend

    # User Frontend
    user-frontend:
        build: ./front-end/user-ui
        container_name: user-frontend
        ports:
            - '3000:80'
        depends_on:
            - backend

volumes:
    mysql_data:
    redis_data:
